// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt5xu0QDeYTMelztwqmDEUf3zRnqX9dRA',
    appId: '1:667508445883:web:778e22a4506f0fe85ccf9e',
    messagingSenderId: '667508445883',
    projectId: 'moviex-91135',
    authDomain: 'moviex-91135.firebaseapp.com',
    storageBucket: 'moviex-91135.firebasestorage.app',
    measurementId: 'G-VY79BRJ191',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpaQmEShKXL-E8DSHzeO-3pliiKhM8qFQ',
    appId: '1:667508445883:android:0b03f8e43a2ef2795ccf9e',
    messagingSenderId: '667508445883',
    projectId: 'moviex-91135',
    storageBucket: 'moviex-91135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE674qVxvWD3gkO17IzUeKZSHviQbZZlY',
    appId: '1:667508445883:ios:04ce6bd7be96d4305ccf9e',
    messagingSenderId: '667508445883',
    projectId: 'moviex-91135',
    storageBucket: 'moviex-91135.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE674qVxvWD3gkO17IzUeKZSHviQbZZlY',
    appId: '1:667508445883:ios:04ce6bd7be96d4305ccf9e',
    messagingSenderId: '667508445883',
    projectId: 'moviex-91135',
    storageBucket: 'moviex-91135.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt5xu0QDeYTMelztwqmDEUf3zRnqX9dRA',
    appId: '1:667508445883:web:b65a1be8acaee4da5ccf9e',
    messagingSenderId: '667508445883',
    projectId: 'moviex-91135',
    authDomain: 'moviex-91135.firebaseapp.com',
    storageBucket: 'moviex-91135.firebasestorage.app',
    measurementId: 'G-5RN5E8RGR3',
  );
}
